# Generated by Django 4.1.8 on 2023-04-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('removeAdultTweets', models.BooleanField(default=False)),
                ('removeAdultImages', models.BooleanField(default=False)),
                ('enforceSafeSearch', models.BooleanField(default=False)),
                ('blockedKeyWords', models.JSONField(blank=True, default=list)),
                ('blockedLinks', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
