# Generated by Django 4.1.8 on 2023-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('word', models.JSONField(blank=True, default=list)),
                ('timestamp', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
